server:
  port: 8080

spring:
  application:
    name: proxy-service
  cloud:
    gateway:
      routes:
        - id: maquette-service
          uri: http://localhost:8081/
          predicates:
            - Path=/**
        - id: repartition-service
          uri: http://localhost:8082/
          predicates:
            - Path=/**
        - id: emploiDutemps-service
          uri: http://localhost:8083/
          predicates:
            - Path=/**

  main:
    web-application-type: reactive

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
